### ISSUE TITLE
GetExperimentRunByName is not designed correctly

### ISSUE THREAD

**Issue by convoliution** [VertaAI/protos-modeldb#2]
[`GetExperimentRunByName`](https://github.com/VertaAI/protos-modeldb/blob/master/protos/public/modeldb/ExperimentRunService.proto#L116) should be similar to [`GetExperimentByName`](https://github.com/VertaAI/protos-modeldb/blob/master/protos/public/modeldb/ExperimentService.proto#L47).

It should have fields:
- `name` for ExperimentRun name
- `experiment_id` for parent experiment ID

It should return:
- `ExperimentRun experiment_run`, not repeated

**Comment by ad-47** [comment]
We have project collaborators so it is possible that the one user creates experimentRun and the second collaborator user has READ-WRITE access so user creating the experimentRun using that same name within the project. In that case, if collaborator user getExperimentRunByName, then that user getting two experimentRuns with the same name in response.

**Comment by convoliution** [comment]
The real problem is that Project, Experiment, and ExperimentRun are all currently implemented differently.

[`GetProjectByName`](https://github.com/VertaAI/protos-modeldb/blob/development/protos/public/modeldb/ProjectService.proto#L128) returns `project_by_user` and `repeated` `shared_projects`.

[`GetExperimentByName`](https://github.com/VertaAI/protos-modeldb/blob/development/protos/public/modeldb/ExperimentService.proto#L51) returns single `experiment`, because the RPC has `name` for the Experiment in addition to `project_id` so the user can specify a Project for the Experiment.

[`GetExperimentRunByName`](https://github.com/VertaAI/protos-modeldb/blob/development/protos/public/modeldb/ExperimentRunService.proto#L118) returns `repeated` `experiment_runs`, because the RPC only has `name` for the ExperimentRun.

Project might be okay to be different, but I don't believe there is a reason why Experiment and ExperimentRun should be different.

**Comment by convoliution** [comment]
> We have project collaborators so it is possible that the one user creates experimentRun and the second collaborator user has READ-WRITE access so user creating the experimentRun using that same name within the project.

A single Project may have two ExperimentRuns with the same name, but a single Experiment would not—even with collaboration. If `GetExperimentRunByName` has a field `experiment_id`, then we can easily identify which ExperimentRun is being requested.
